// ============================================================
// Vibehouse - Real Product & Content Data
// ============================================================
// TODO: Replace with Supabase fetch: supabase.from('products').select('*')
// TODO: Firebase Auth + Firestore for user data

const PRODUCTS = [
  {
    id: "inbox-sorter",
    logoColor: "#6c5ce7",
    ownerColor: "#e17055",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Inbox Sorter",
    type: "SaaS tool",
    category: "Productivity",
    price: "$12/mo",
    priceValue: 12,
    desc: "Sorts your email into what needs a reply today and what can wait, and drafts the replies for you.",
    longDesc: "Inbox Sorter uses advanced NLP to categorize every incoming email by urgency and intent. It surfaces the 3-5 messages that actually need your attention today, auto-drafts professional replies, and quietly archives the rest. Perfect for founders and operators drowning in inbox zero theater.",
    owner: "Aarav Mehta",
    ownerId: "aarav-mehta",
    ownerRole: "Founder & Engineer",
    ownerBio: "Ex-Google, now building tools that give people their time back. Based in Bangalore.",
    tags: ["email", "automation", "productivity"],
    features: ["Smart prioritization", "AI reply drafts", "Daily digest", "Gmail & Outlook support", "Custom rules"],
    screenshots: ["inbox-1.png", "inbox-2.png"],
    video: null,
    pdf: null,
    intro: "I built Inbox Sorter after spending 2 hours every morning just triaging email. Now I open my laptop and the important stuff is already highlighted.",
    status: "live",
    waitlist: false,
    users: 2840,
    rating: 4.8,
    launched: "2025-11-12"
  },
  {
    id: "pocket-ledger",
    logoColor: "#00b894",
    ownerColor: "#fd79a8",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Pocket Ledger",
    type: "Mobile app",
    category: "Finance",
    price: "$4.99/mo",
    priceValue: 4.99,
    desc: "Log a purchase by speaking it. See where the month's money went without typing a number.",
    longDesc: "Pocket Ledger turns voice notes into clean expense entries. Say “coffee 180 rupees” and it categorizes, converts currency if needed, and updates your monthly dashboard. No receipts, no typing, just talk.",
    owner: "Diya Rao",
    ownerId: "diya-rao",
    ownerRole: "Product Designer",
    ownerBio: "Design systems nerd who believes finance apps should feel like talking to a friend.",
    tags: ["finance", "voice", "mobile"],
    features: ["Voice logging", "Smart categories", "Monthly insights", "Multi-currency", "Export CSV"],
    screenshots: ["ledger-1.png"],
    video: null,
    pdf: null,
    intro: "I hate typing numbers into expense apps. So I made one that listens.",
    status: "live",
    waitlist: false,
    users: 9120,
    rating: 4.7,
    launched: "2025-09-03"
  },
  {
    id: "menu-maker",
    logoColor: "#0984e3",
    ownerColor: "#00cec9",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Menu Maker",
    type: "Website",
    category: "Business",
    price: "$19/mo",
    priceValue: 19,
    desc: "Turns a cafe's or restaurant's menu into a fast, mobile-ready website that updates when the menu does.",
    longDesc: "Upload a photo or paste a Google Doc of your menu. Menu Maker generates a beautiful, SEO-friendly, mobile-first website in under 60 seconds. Change a price or add a dish and the live site updates instantly. No code, no designer needed.",
    owner: "Kabir Sethi",
    ownerId: "kabir-sethi",
    ownerRole: "Full-stack Builder",
    ownerBio: "Helping local businesses look world-class online without agency prices.",
    tags: ["restaurant", "website", "no-code"],
    features: ["Photo-to-menu", "Instant updates", "QR code menu", "Multi-language", "Analytics"],
    screenshots: ["menu-1.png", "menu-2.png"],
    video: "assets/menu-maker-demo.mp4",
    pdf: null,
    intro: "My uncle’s café had a paper menu that was always outdated. This fixes that forever.",
    status: "live",
    waitlist: false,
    users: 1560,
    rating: 4.9,
    launched: "2026-01-18"
  },
  {
    id: "standup-bot",
    logoColor: "#e17055",
    ownerColor: "#fdcb6e",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Standup Bot",
    type: "Web app",
    category: "Team",
    price: "$8/mo",
    priceValue: 8,
    desc: "Collects each teammate's daily update in chat and posts one clean summary before the morning meeting.",
    longDesc: "Standup Bot lives in Slack or Discord. It pings the team at a set time, collects what everyone worked on / is blocked on, and posts a single clean thread summary 10 minutes before standup. Saves 15-20 minutes every day.",
    owner: "Meera Iyer",
    ownerId: "meera-iyer",
    ownerRole: "Engineering Manager",
    ownerBio: "Remote-first team lead who hates status meetings that could have been a message.",
    tags: ["slack", "team", "automation"],
    features: ["Slack & Discord", "Smart summarization", "Blocker detection", "Async by default", "History search"],
    screenshots: ["standup-1.png"],
    video: null,
    pdf: null,
    intro: "We used to spend the first 15 minutes of every standup just collecting updates. Not anymore.",
    status: "live",
    waitlist: false,
    users: 4200,
    rating: 4.6,
    launched: "2025-12-02"
  },
  {
    id: "invoice-nest",
    logoColor: "#fd79a8",
    ownerColor: "#a29bfe",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Invoice Nest",
    type: "SaaS tool",
    category: "Finance",
    price: "$15/mo",
    priceValue: 15,
    desc: "Create invoices, send them, and chase late payments automatically. Built for solo workers and small studios.",
    longDesc: "Invoice Nest is the billing tool freelancers actually finish setting up. Beautiful templates, one-click send, automatic payment reminders, and a simple dashboard that shows who still owes you money. Integrates with Stripe and Razorpay.",
    owner: "Rohan Das",
    ownerId: "rohan-das",
    ownerRole: "Indie Hacker",
    ownerBio: "Serial bootstrapper. Built three profitable tools while still freelancing.",
    tags: ["invoicing", "freelance", "payments"],
    features: ["Beautiful templates", "Auto reminders", "Stripe + Razorpay", "Expense tracking", "Tax-ready reports"],
    screenshots: ["invoice-1.png"],
    video: null,
    pdf: "invoice-nest-guide.pdf",
    intro: "I was tired of awkward ‘just following up on the invoice’ emails. Now the robot does it.",
    status: "live",
    waitlist: false,
    users: 3780,
    rating: 4.8,
    launched: "2025-10-21"
  },
  {
    id: "habit-orchard",
    logoColor: "#00cec9",
    ownerColor: "#55efc4",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Habit Orchard",
    type: "Mobile app",
    category: "Health",
    price: "$3.99/mo",
    priceValue: 3.99,
    desc: "Grow a small tree for every habit you keep. Missed days don't reset it, they just slow its growth.",
    longDesc: "Most habit apps punish you for missing a day. Habit Orchard treats consistency as a forest that grows slowly. Each streak grows a tree. Miss a day and the tree just grows slower. Beautiful, kind, and actually sustainable.",
    owner: "Ishita Nair",
    ownerId: "ishita-nair",
    ownerRole: "Behavioral Designer",
    ownerBio: "Psychology + design. Building products that work with human nature, not against it.",
    tags: ["habits", "wellness", "mobile"],
    features: ["Visual forest", "No streak shame", "Gentle reminders", "Social orchards", "Apple Health sync"],
    screenshots: ["habit-1.png", "habit-2.png"],
    video: null,
    pdf: null,
    intro: "I deleted every habit tracker that reset my streak to zero. This one never does.",
    status: "live",
    waitlist: false,
    users: 12400,
    rating: 4.9,
    launched: "2025-08-14"
  },
  {
    id: "launch-pages",
    logoColor: "#fdcb6e",
    ownerColor: "#74b9ff",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Launch Pages",
    type: "Website",
    category: "Marketing",
    price: "$9/mo",
    priceValue: 9,
    desc: "One-page sites for product launches, with a built-in waitlist and a link that previews well when shared.",
    longDesc: "Launch Pages lets you spin up a polished waitlist or launch page in minutes. Beautiful templates, built-in email capture, social preview cards that actually look good, and analytics so you know when to hit ‘go live’.",
    owner: "Neil Banerjee",
    ownerId: "neil-banerjee",
    ownerRole: "Growth Engineer",
    ownerBio: "Helped 40+ indie products hit Product Hunt #1. Now productizing the process.",
    tags: ["launch", "waitlist", "landing-page"],
    features: ["Waitlist built-in", "Social cards", "A/B templates", "Email export", "Custom domain"],
    screenshots: ["launch-1.png"],
    video: null,
    pdf: null,
    intro: "Every product needs a home before it ships. This is the fastest way to get one.",
    status: "live",
    waitlist: false,
    users: 6100,
    rating: 4.7,
    launched: "2025-11-28"
  },
  {
    id: "clip-notes",
    logoColor: "#a29bfe",
    ownerColor: "#ff7675",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Clip Notes",
    type: "Web app",
    category: "Productivity",
    price: "$7/mo",
    priceValue: 7,
    desc: "Save snippets from any page and ask questions across everything you've collected.",
    longDesc: "Clip Notes is your second brain for the web. Highlight text, save it with one click, then ask natural language questions across your entire collection. Perfect for researchers, writers, and anyone who reads a lot.",
    owner: "Sana Qureshi",
    ownerId: "sana-qureshi",
    ownerRole: "AI Researcher",
    ownerBio: "PhD dropout who decided building useful tools was more fun than writing papers.",
    tags: ["notes", "research", "ai"],
    features: ["Web clipper", "Semantic search", "Ask your notes", "Tags & folders", "Export Markdown"],
    screenshots: ["clip-1.png"],
    video: null,
    pdf: null,
    intro: "I had 400 browser tabs and zero memory of what was in them. Clip Notes fixed both.",
    status: "live",
    waitlist: false,
    users: 8900,
    rating: 4.8,
    launched: "2026-02-05"
  },
  // More products
  {
    id: "daxeon",
    logoColor: "#55efc4",
    ownerColor: "#ffeaa7",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Daxeon",
    type: "SaaS tool",
    category: "Security",
    price: "$20/mo",
    priceValue: 20,
    desc: "Scam protection for Discord communities. Content moderation that actually works.",
    longDesc: "Daxeon sits inside your Discord server and stops scam links, phishing, and malicious bots before they spread. Real-time content moderation powered by a model trained on actual Discord attack patterns.",
    owner: "Joshua Marchand",
    ownerId: "joshua-marchand",
    ownerRole: "Security Engineer",
    ownerBio: "Former Discord Trust & Safety. Building the tools I wish we had.",
    tags: ["discord", "security", "moderation"],
    features: ["Link scanning", "Bot detection", "Auto-mod rules", "Admin dashboard", "Appeal flow"],
    screenshots: [],
    video: null,
    pdf: null,
    intro: "I watched too many servers get raided. Daxeon is the shield I wish every community had.",
    status: "live",
    waitlist: false,
    users: 3400,
    rating: 4.9,
    launched: "2026-03-01"
  },
  {
    id: "todo-is",
    logoColor: "#74b9ff",
    ownerColor: "#6c5ce7",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "ToDo.is",
    type: "SaaS tool",
    category: "Productivity",
    price: "$29/mo",
    priceValue: 29,
    desc: "The ultimate to-do list app for tasks and projects. Task automation that feels natural.",
    longDesc: "ToDo.is combines classic task management with lightweight automation. Create recurring workflows, assign to teammates, and let the AI suggest the next best action based on your patterns.",
    owner: "Abdelmalek Ezzaky",
    ownerId: "abdelmalek-ezzaky",
    ownerRole: "Product Builder",
    ownerBio: "Obsessed with systems that remove friction from daily work.",
    tags: ["tasks", "automation", "team"],
    features: ["Smart recurring", "Team boards", "AI suggestions", "Calendar sync", "Integrations"],
    screenshots: [],
    video: null,
    pdf: null,
    intro: "I tried every todo app. Then I built the one that actually stuck.",
    status: "live",
    waitlist: false,
    users: 5200,
    rating: 4.6,
    launched: "2025-12-15"
  },
  {
    id: "motqn",
    logoColor: "#ff7675",
    ownerColor: "#00b894",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "Motqn",
    type: "SaaS tool",
    category: "Education",
    price: "$4.99/mo",
    priceValue: 4.99,
    desc: "AI lesson prep for teachers, built by voice. Teaching made lighter.",
    longDesc: "Motqn lets teachers speak a topic and instantly receive a structured lesson plan, slides outline, quiz, and differentiation ideas. Built by educators for educators.",
    owner: "Zeyad Al Mothafar",
    ownerId: "zeyad-al-mothafar",
    ownerRole: "EdTech Founder",
    ownerBio: "Former teacher. Now building the tools I needed in the classroom.",
    tags: ["education", "teachers", "voice"],
    features: ["Voice to lesson", "Quiz generator", "Differentiation", "Curriculum aligned", "Export PDF"],
    screenshots: [],
    video: null,
    pdf: null,
    intro: "Lesson planning used to take my entire Sunday. Now it takes 12 minutes.",
    status: "live",
    waitlist: false,
    users: 7800,
    rating: 4.8,
    launched: "2026-01-09"
  },
  {
    id: "reference-checker",
    logoColor: "#ffeaa7",
    ownerColor: "#0984e3",
    logoUrl: null,
    ownerAvatarUrl: null,
    name: "ReferenceChecker.ai",
    type: "Web app",
    category: "Research",
    price: "Free",
    priceValue: 0,
    desc: "Catch citation errors instantly, for free. Citation verification that actually works.",
    longDesc: "Paste your bibliography or upload a PDF. ReferenceChecker.ai verifies every citation against major academic databases and flags missing DOIs, broken links, and formatting issues in seconds.",
    owner: "Nick Avle",
    ownerId: "nick-avle",
    ownerRole: "Academic Tools",
    ownerBio: "PhD candidate who got tired of citation hell.",
    tags: ["citations", "research", "academic"],
    features: ["DOI lookup", "Format check", "Broken link detection", "APA/MLA/Chicago", "Batch mode"],
    screenshots: [],
    video: null,
    pdf: null,
    intro: "I once spent 6 hours fixing citations. Never again.",
    status: "live",
    waitlist: false,
    users: 15600,
    rating: 4.7,
    launched: "2025-10-30"
  }
];

const NEWS = [
  {
    id: "n1",
    logoColor: "#6c5ce7",
    ownerColor: "#e17055",
    logoUrl: null,
    ownerAvatarUrl: null,
    title: "Will America Spend 9% of Its GDP on AI? The Industry Is Counting on It",
    source: "The Wall Street Journal",
    tag: "Spending",
    time: "1h",
    votes: 15,
    type: "article"
  },
  {
    id: "n2",
    logoColor: "#00b894",
    ownerColor: "#fd79a8",
    logoUrl: null,
    ownerAvatarUrl: null,
    title: "Your AI's Plan = The Problem",
    source: "Vibehouse",
    tag: "Planning",
    time: "7h",
    votes: 168,
    type: "article"
  },
  {
    id: "n3",
    logoColor: "#0984e3",
    ownerColor: "#00cec9",
    logoUrl: null,
    ownerAvatarUrl: null,
    title: "Apple to Tighten Mac Data Controls in Guard Against AI Agents",
    source: "Bloomberg",
    tag: "Apple",
    time: "8h",
    votes: 78,
    type: "article"
  },
  {
    id: "n4",
    logoColor: "#e17055",
    ownerColor: "#fdcb6e",
    logoUrl: null,
    ownerAvatarUrl: null,
    title: "CA tech executive arrested for allegedly smuggling $300M in Nvidia chips to CN",
    source: "Quartz",
    tag: "International Trade",
    time: "10h",
    votes: 74,
    type: "article"
  },
  {
    id: "n5",
    logoColor: "#fd79a8",
    ownerColor: "#a29bfe",
    logoUrl: null,
    ownerAvatarUrl: null,
    title: "Why AI Leaders Have Changed Their Minds About AI Safety",
    source: "Peter H. Diamandis",
    tag: "Research",
    time: "11h",
    votes: 123000,
    type: "video",
    duration: "23:49"
  },
  {
    id: "n6",
    logoColor: "#00cec9",
    ownerColor: "#55efc4",
    logoUrl: null,
    ownerAvatarUrl: null,
    title: "Vercel CEO reveals his Agentic Engineering Workflow",
    source: "David Ondrej",
    tag: "Agents",
    time: "15h",
    votes: 68,
    type: "video",
    duration: "1h 37m"
  },
  {
    id: "n7",
    logoColor: "#fdcb6e",
    ownerColor: "#74b9ff",
    logoUrl: null,
    ownerAvatarUrl: null,
    title: "Reddit to sunset RSS access because of AI bots",
    source: "The Verge",
    tag: "Bots",
    time: "16h",
    votes: 226,
    type: "article"
  },
  {
    id: "n8",
    logoColor: "#a29bfe",
    ownerColor: "#ff7675",
    logoUrl: null,
    ownerAvatarUrl: null,
    title: "Who’s to Blame When A.I. Goes Rogue?",
    source: "The New York Times",
    tag: "Liability",
    time: "20h",
    votes: 7,
    type: "article"
  }
];

const TASKS_DEFAULT = [
  { id: "t1", title: "Ship Inbox Sorter v1.2 with Outlook support", done: false, due: "2026-10-10" },
  { id: "t2", title: "Record demo video for Menu Maker", done: true, due: "2026-10-01" },
  { id: "t3", title: "Write launch post for Habit Orchard", done: false, due: "2026-10-08" },
  { id: "t4", title: "Review Daxeon security audit", done: false, due: "2026-10-12" },
  { id: "t5", title: "Add Stripe billing to Invoice Nest", done: true, due: "2026-09-28" }
];

const STATS = {
  tools: 54021,
  devices: 377,
  robots: 718,
  news: 15879,
  videos: 11595,
  models: 1752,
  companies: 9321,
  countries: 114,
  tasks: 10797,
  repositories: 46913,
  fundraises: 2721,
  investors: 2423,
  collections: 14124
};

// Current user mock (localStorage will override)
const DEFAULT_USER = {
  name: "Linkan",
  email: "linkan@vibehouse.com",
  avatar: "L",
  tools: 0,
  karma: 0,
  joined: "2025-11-01",
  bio: "Building in public. Vibe coder."
};
